export const routerList = [{
    'text': 'start',
    'routerLink': '/start',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'typography',
    'routerLink': '',
    'routerLinkActive': '',
    'class': 'list-item list-item-desc'
}, {
    'text': 'typography',
    'routerLink': '/typography',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'icons',
    'routerLink': '',
    'routerLinkActive': '',
    'class': 'list-item list-item-desc'
}, {
    'text': 'icons',
    'routerLink': '/icons',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'Data Entry',
    'routerLink': '',
    'routerLinkActive': '',
    'class': 'list-item list-item-desc'
}, {
    'text': 'box-group',
    'routerLink': '/components/box-group',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'calendar',
    'routerLink': '/components/calendar',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'chips',
    'routerLink': '/components/chips',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'input',
    'routerLink': '/components/input',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'region',
    'routerLink': '/components/region',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'select',
    'routerLink': '/components/select',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'schedule',
    'routerLink': '/components/schedule',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'search-box',
    'routerLink': '/components/search-box',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'slider',
    'routerLink': '/components/slider',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'spinner',
    'routerLink': '/components/spinner',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'switch',
    'routerLink': '/components/switch',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'textarea',
    'routerLink': '/components/textarea',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'text-line',
    'routerLink': '/components/text-line',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'transfer',
    'routerLink': '/components/transfer',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'rating',
    'routerLink': '/components/rating',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'Navigation',
    'routerLink': '',
    'routerLinkActive': '',
    'class': 'list-item list-item-desc'
}, {
    'text': 'breadcrumb',
    'routerLink': '/components/breadcrumb',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'page',
    'routerLink': '/components/page',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'side-bar',
    'routerLink': '/components/side-bar',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'step',
    'routerLink': '/components/step',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'tabs',
    'routerLink': '/components/tabs',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'tree',
    'routerLink': '/components/tree',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'Button',
    'routerLink': '',
    'routerLinkActive': '',
    'class': 'list-item list-item-desc'
}, {
    'text': 'button',
    'routerLink': '/components/button',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'button-group',
    'routerLink': '/components/button-group',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'Chart',
    'routerLink': '',
    'routerLinkActive': '',
    'class': 'list-item list-item-desc'
}, {
    'text': 'chart',
    'routerLink': '/components/chart',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'Data',
    'routerLink': '',
    'routerLinkActive': '',
    'class': 'list-item list-item-desc'
}, {
    'text': 'table',
    'routerLink': '/components/table',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'Grid',
    'routerLink': '',
    'routerLinkActive': '',
    'class': 'list-item list-item-desc'
}, {
    'text': 'grid',
    'routerLink': '/components/grid',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'Overlay',
    'routerLink': '',
    'routerLinkActive': '',
    'class': 'list-item list-item-desc'
}, {
    'text': 'dialog',
    'routerLink': '/components/dialog',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'toast',
    'routerLink': '/components/toast',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'tooltip',
    'routerLink': '/components/tooltip',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'Containers',
    'routerLink': '',
    'routerLinkActive': '',
    'class': 'list-item list-item-desc'
}, {
    'text': 'accordion',
    'routerLink': '/components/accordion',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'card',
    'routerLink': '/components/card',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'Uploader',
    'routerLink': '',
    'routerLinkActive': '',
    'class': 'list-item list-item-desc'
}, {
    'text': 'uploader',
    'routerLink': '/components/uploader',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'Utilities',
    'routerLink': '',
    'routerLinkActive': '',
    'class': 'list-item list-item-desc'
}, {
    'text': 'code-highlighter',
    'routerLink': '/components/code-highlighter',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'code-box',
    'routerLink': '/components/code-box',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'carousel',
    'routerLink': '/components/carousel',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'progress-bar',
    'routerLink': '/components/progress-bar',
    'routerLinkActive': 'active',
    'class': 'list-item'
}, {
    'text': 'Form',
    'routerLink': '',
    'routerLinkActive': '',
    'class': 'list-item list-item-desc'
}, {
    'text': 'form',
    'routerLink': '/components/form',
    'routerLinkActive': 'active',
    'class': 'list-item'
}];
